# Generated by Django 2.2.5 on 2020-02-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='cCommunication',
            new_name='communication',
        ),
    ]
